server: 
  port: 9009
spring: 
  application:  
    name: tensquare-sms #指定服务名
  rabbitmq:
    host: 192.168.17.128
aliyun:
  sms:
    accessKeyId: LTAIdUzLci9KmN5F
    accessKeySecret: mIfBE2NtTAGstiyq52a63OPkZTxN2D
    template_code: SMS_152283891
    sign_name: 香蕉c
